package edu.iastate.locampus.role;

public enum Permission {
    USER_LIST,
    USER_DELETE,
    USER_DELETE_ANY,
    USER_EXISTS,
    USER_GET_ROLES,
    USER_GET_BADGES,
    USER_SET_BIO,
    USER_SET_BIO_ANY,
    USER_GET_BIO,
    USER_GET_POSTS,
    USER_SET_FOLLOWERS,
    USER_SET_FOLLOWERS_ANY,
    USER_REQUEST_FRIEND,
    USER_REQUEST_FRIEND_ANY,
    USER_REM_REQUEST_FRIEND,
    USER_REM_REQUEST_FRIEND_ANY,
    USER_ADD_FRIEND,
    USER_ADD_FRIEND_ANY,
    USER_REMOVE_FRIEND,
    USER_REMOVE_FRIEND_ANY,

    POST_CREATE,
    POST_DELETE,
    POST_SET_CONTENT,
    POST_RANK,
    POST_LIST,

    ROLE_CREATE,
    ROLE_DELETE,
    ROLE_GET_PERMISSIONS,
    ROLE_ADD_PERMISSION,
    ROLE_REMOVE_PERMISSION
}